# Generated by Django 2.0.6 on 2018-06-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('twitter_token', models.CharField(max_length=200)),
                ('twitter_token_sercret', models.CharField(max_length=200)),
            ],
        ),
    ]
